import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Plants Fresher',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'guest': 'Continue as Guest',
      'home': 'Home',
      'catalog': 'Catalog',
      'cart': 'Cart',
      'profile': 'Profile',
      'search': 'Search plants, tags...',
      'add_to_cart': 'Add to cart',
      'add_to_compare': 'Add to compare',
      'ai_info': 'AI Info',
      'compare': 'Compare',
      'empty_compare': 'No plants to compare yet',
      'clear_all': 'Clear all',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery fee',
      'total': 'Total',
      'pay': 'Pay',
      'theme': 'Theme',
      'language': 'Language',
      'dark_mode': 'Dark mode',
      'primary_color': 'Primary color',
      'logout': 'Logout',
      'welcome': 'Welcome',
      'hi_guest': 'Hi plant lover',
      'checkout': 'Checkout',
      'orders': 'Orders',
      'success_title': 'Congratulations!',
      'success_subtitle': 'Your order is successfully placed',
      'back_home': 'Back to Home',
      'view_orders': 'View Orders',
      'promo_code': 'Promo code',
      'apply': 'Apply',
      'saved_cards': 'Saved cards',
      'add_card': 'Add new card',
      'stores': 'Stores',
      'empty_cart': 'Your cart is empty',
      'categories': 'Categories',
      'featured': 'Featured',
      'indoor': 'Indoor',
      'outdoor': 'Outdoor',
      'flowers': 'Flowers',
      'tools': 'Tools',
      'load_more': 'Load more',
      'system_mode': 'System',
      'pay_securely': 'Pay securely',
      'card_holder': 'Card holder',
      'card_number': 'Card number',
      'expiry': 'Expiry',
      'cvc': 'CVC',
      'save_card': 'Save card for later',
      'ai_mock_title': 'AI Insights (mock)',
      'ai_mock_body': 'Future AI tips will appear here with personalized advice.',
      'table_property': 'Property',
      'table_price': 'Price',
      'table_height': 'Height',
      'table_temperature': 'Temperature',
      'table_humidity': 'Humidity',
    },
    'ar': {
      'app_name': 'بلانتس فريشر',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'guest': 'الدخول كضيف',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'cart': 'السلة',
      'profile': 'الملف الشخصي',
      'search': 'ابحث عن النباتات أو العلامات...',
      'add_to_cart': 'أضف للسلة',
      'add_to_compare': 'أضف للمقارنة',
      'ai_info': 'معلومات بالذكاء الاصطناعي',
      'compare': 'مقارنة',
      'empty_compare': 'لا توجد نباتات للمقارنة بعد',
      'clear_all': 'مسح الكل',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'pay': 'ادفع',
      'theme': 'المظهر',
      'language': 'اللغة',
      'dark_mode': 'الوضع الليلي',
      'primary_color': 'اللون الأساسي',
      'logout': 'تسجيل الخروج',
      'welcome': 'أهلاً بك',
      'hi_guest': 'مرحباً محب النباتات',
      'checkout': 'إتمام الشراء',
      'orders': 'الطلبات',
      'success_title': 'تهانينا!',
      'success_subtitle': 'تم تنفيذ طلبك بنجاح',
      'back_home': 'العودة للرئيسية',
      'view_orders': 'عرض الطلبات',
      'promo_code': 'رمز الخصم',
      'apply': 'تطبيق',
      'saved_cards': 'البطاقات المحفوظة',
      'add_card': 'أضف بطاقة جديدة',
      'stores': 'الفروع',
      'empty_cart': 'سلتك فارغة',
      'categories': 'التصنيفات',
      'featured': 'مميزة',
      'indoor': 'داخلي',
      'outdoor': 'خارجي',
      'flowers': 'زهور',
      'tools': 'أدوات',
      'load_more': 'المزيد',
      'system_mode': 'حسب النظام',
      'pay_securely': 'ادفع بأمان',
      'card_holder': 'صاحب البطاقة',
      'card_number': 'رقم البطاقة',
      'expiry': 'انتهاء',
      'cvc': 'رمز الأمان',
      'save_card': 'حفظ البطاقة لاحقاً',
      'ai_mock_title': 'معلومات بالذكاء الاصطناعي (تجريبية)',
      'ai_mock_body': 'ستظهر النصائح الذكية هنا مستقبلاً بدون أي طلبات خارجية.',
      'table_property': 'خاصية',
      'table_price': 'السعر',
      'table_height': 'الارتفاع',
      'table_temperature': 'درجة الحرارة',
      'table_humidity': 'الرطوبة',
    },
  };

  String t(String key) => _localizedValues[locale.languageCode]?[key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
