import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Plants Fresher',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'guest': 'Continue as Guest',
      'home': 'Home',
      'catalog': 'Catalog',
      'cart': 'Cart',
      'profile': 'Profile',
      'search': 'Search plants, tags...',
      'add_to_cart': 'Add to cart',
      'add_to_compare': 'Add to compare',
      'ai_info': 'AI Info',
      'compare': 'Compare',
      'empty_compare': 'No plants to compare yet',
      'clear_all': 'Clear all',
      'favorites': 'Favorites',
      'empty_favorites': 'Save plants you love to find them faster later.',
      'guides': 'Guides',
      'search_guides': 'Search care guides...',
      'empty_guides': 'No guides found for your filters yet',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery fee',
      'total': 'Total',
      'pay': 'Pay',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'theme': 'Theme',
      'language': 'Language',
      'dark_mode': 'Dark mode',
      'primary_color': 'Primary color',
      'logout': 'Logout',
      'welcome': 'Welcome',
      'hi_guest': 'Hi plant lover',
      'checkout': 'Checkout',
      'orders': 'Orders',
      'success_title': 'Congratulations!',
      'success_subtitle': 'Your order is successfully placed',
      'back_home': 'Back to Home',
      'view_orders': 'View Orders',
      'promo_code': 'Promo code',
      'apply': 'Apply',
      'apply_now': 'Apply now',
      'coupons': 'Coupons',
      'coupon_center': 'Coupon center',
      'browse_coupons': 'Browse coupons',
      'applied_coupon': 'Applied {code}',
      'coupon_applied': 'Coupon {code} applied for {value}',
      'invalid_coupon': 'Invalid coupon',
      'expired_coupon': 'Coupon expired',
      'min_spend_coupon': 'Requires a minimum of {min}',
      'min_spend': 'Min spend {min}',
      'discount': 'Discount',
      'saved_cards': 'Saved cards',
      'add_card': 'Add new card',
      'stores': 'Stores',
      'addresses': 'Addresses',
      'manage_addresses': 'Manage addresses',
      'shipping_address': 'Shipping address',
      'add_address': 'Add address',
      'empty_addresses': 'No addresses yet. Add one to speed up checkout.',
      'empty_cart': 'Your cart is empty',
      'categories': 'Categories',
      'featured': 'Featured',
      'recently_viewed': 'Recently viewed',
      'empty_recent': 'View some plants to fill this space with your picks.',
      'journal': 'Journal',
      'journal_hint': 'Log wins, routines, and plant moods.',
      'empty_journal': 'No journal entries yet. Capture your first plant story.',
      'add_entry': 'Add entry',
      'new_entry': 'New entry',
      'title_hint': 'Title',
      'note_hint': 'What happened?',
      'save_entry': 'Save entry',
      'insights': 'Insights',
      'insights_entry': 'Care streaks, spend, and favorites in one dashboard.',
      'impact_overview': 'Impact overview',
      'total_spend': 'Total spend',
      'care_streak': 'Care streak',
      'care_streak_body': 'Stay on track with watering, misting, and feeding.',
      'care_completed': 'tasks completed',
      'care_now_hint': 'Keep the streak',
      'week_view': 'Week view',
      'hydration_chart': 'Hydration (L)',
      'sun_chart': 'Sunlight (hrs)',
      'recent_activity': 'Recent activity',
      'insight_highlights': 'Highlights',
      'carbon_offset': 'Greener footprint',
      'carbon_offset_body': 'Your indoor jungle is offsetting a few kg of CO₂ monthly.',
      'care_win': 'Care wins',
      'care_win_body': 'Short sessions add up—micro tasks keep plants thriving.',
      'restock_hint': 'Shop smarter',
      'restock_hint_body': 'Bundles and coupons lower delivery fees on your next haul.',
      'orders_count': '{count} orders tracked',
      'favorites_count': '{count} favorites saved',
      'favorites_body': 'Save plants you love to tailor tips and recommendations.',
      'last_viewed': 'Last viewed: {name}',
      'recent_prompt': 'Jump back into details or add to cart.',
      'bundle_story': 'Bundle highlights',
      'calm': 'Calm',
      'thriving': 'Thriving',
      'sensitive': 'Sensitive',
      'glossy': 'Glossy',
      'whats_new': "What's new",
      'updates_hint': 'See the latest release notes and tweaks.',
      'mark_all_read': 'Mark read',
      'new': 'New',
      'indoor': 'Indoor',
      'outdoor': 'Outdoor',
      'flowers': 'Flowers',
      'cactus': 'Cactus',
      'tools': 'Tools',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'load_more': 'Load more',
      'system_mode': 'System',
      'added_favorite': 'Added to favorites',
      'removed_favorite': 'Removed from favorites',
      'pay_securely': 'Pay securely',
      'card_holder': 'Card holder',
      'card_number': 'Card number',
      'expiry': 'Expiry',
      'cvc': 'CVC',
      'save_card': 'Save card for later',
      'label_hint': 'Label (Home, Office...)',
      'full_name': 'Full name',
      'phone': 'Phone',
      'city': 'City',
      'street': 'Street',
      'set_default': 'Set as default',
      'default_address': 'Default',
      'save': 'Save',
      'ai_mock_title': 'AI Insights (mock)',
      'ai_mock_body': 'Future AI tips will appear here with personalized advice.',
      'diagnostics': 'Plant doctor',
      'diagnostics_headline': 'Fix issues faster',
      'diagnostics_subtitle': 'Spot symptoms, mark fixes, and keep leaves happy.',
      'severity_all': 'All',
      'severity_low': 'Low',
      'severity_medium': 'Medium',
      'severity_high': 'High',
      'table_property': 'Property',
      'table_price': 'Price',
      'table_height': 'Height',
      'table_temperature': 'Temperature',
      'table_humidity': 'Humidity',
      'empty_catalog': 'No plants match your filters yet',
      'all': 'All',
      'clear': 'Clear',
      'open': 'Open',
      'read_now': 'Read now',
      'completed': 'Completed',
      'minutes': 'min',
      'close': 'Close',
      'about': 'About',
      'about_description': 'Plants Fresher is a mock shopping experience with smooth animations and bilingual support.',
      'about_highlights': 'Highlights',
      'about_feature_theme': 'Custom themes, dark mode, and primary color picker',
      'about_feature_compare': 'Compare up to three plants side-by-side',
      'about_feature_checkout': 'Cart, promo, and checkout flows without external APIs',
      'about_feature_localization': 'English and Arabic with RTL layout mirroring',
      'contact': 'Contact',
      'contact_email': 'support@plantsfresher.app',
      'contact_message': 'Reach out anytime for feedback or feature requests.',
      'version_1': 'v1.0 mock',
      'built_with_flutter': 'Built with Flutter',
      'guest_user': 'Guest user',
      'member_user': 'Signed in',
      'order_date': 'Order date',
      'order_status': 'Status',
      'status_processing': 'Processing',
      'status_packed': 'Packed',
      'status_shipped': 'Shipped',
      'status_out_for_delivery': 'Out for delivery',
      'status_delivered': 'Delivered',
      'track_order': 'Track order',
      'order_timeline': 'Order timeline',
      'order_progress': 'Progress',
      'tracking_updates': 'Tracking updates',
      'estimated_delivery': 'Est. delivery',
      'checkpoint_placed': 'Order placed',
      'checkpoint_packed': 'Packed at warehouse',
      'checkpoint_shipped': 'Shipped',
      'checkpoint_out_for_delivery': 'Out for delivery',
      'checkpoint_delivered': 'Delivered',
      'track_hint': 'Follow every step until your plants arrive.',
      'reorder': 'Reorder',
      'downtown_branch': 'Downtown branch',
      'uptown_branch': 'Uptown branch',
      'harbor_branch': 'Harbor branch',
      'added_to_cart': 'Items added to cart',
      'care_schedule': 'Care schedule',
      'care_calendar': 'Care calendar',
      'care_overview': 'Care at a glance',
      'care_overview_subtitle': 'Tap a date to see watering and misting tasks.',
      'due_today': '{count} due today',
      'upcoming_tasks': '{count} upcoming',
      'open_calendar': 'Open calendar',
      'due_tasks_for': 'Tasks for {date}',
      'no_tasks_day': 'No tasks for this day. Enjoy a calm schedule!',
      'month_label': '{month} · {year}',
      'calendar_shortcut': 'View monthly care calendar',
      'care_headline': 'Keep plants thriving',
      'care_subtitle': 'Reminders for watering, misting, and rotating at the right time.',
      'view_up_next': 'View up next',
      'up_next': 'Up next',
      'due_now': 'Due now',
      'due_in_hours': 'Due in {hours}h',
      'due_in_days': 'Due in {days}d',
      'snooze': 'Snooze',
      'care_empty': 'No care tasks yet—add plants to start tracking!',
      'rewards': 'Rewards',
      'your_points': 'Your points',
      'next_reward_hint': 'Keep caring for plants to unlock your next perk.',
      'earned_badges': 'Earned badges',
      'no_badges': 'No badges yet—complete actions to earn them.',
      'reset_badges': 'Reset badges',
      'quick_actions': 'Quick actions',
      'finish_guide': 'Finish a guide',
      'complete_care': 'Complete a care task',
      'favorite_plant': 'Add a favorite plant',
      'points_added': 'Points added!',
      'redeem': 'Redeem',
      'free_delivery': 'Free delivery',
      'pot_upgrade': 'Pot upgrade',
      'surprise_seed': 'Surprise seed pack',
      'redeemed': 'Redeemed! Enjoy your perk.',
      'pts': 'pts',
      'view_rewards': 'View rewards',
      'reward_hint': 'Redeem perks for points',
      'referrals': 'Referrals',
      'invite_title': 'Invite friends, grow together',
      'invite_body': 'Share your code to earn bonus points when they order.',
      'invite_hint': 'Share your code to earn bonuses.',
      'share_now': 'Share now',
      'share_code': 'Your code',
      'copied': 'Copied',
      'share_hint': 'Share link copied to use anywhere.',
      'joined_mock': 'Marked a friend as joined',
      'invites_sent': 'Invites sent',
      'friends_joined': 'Friends joined',
      'reward_points': 'Reward points',
      'how_it_works': 'How it works',
      'refer_step1': 'Share your invite link or code.',
      'refer_step2': 'Friends place their first order.',
      'refer_step3': 'You both earn points to redeem perks.',
      'explore_guides': 'Care guides',
      'micro_lessons': 'Micro-lessons for plant wins',
      'bundles': 'Bundles',
      'bundle_headline': 'Curated bundles to gift or glow up a room',
      'bundle_subtitle': 'Ready-to-ship sets with pots and cards.',
      'great_value': 'Great value',
      'curated_sets': 'Curated sets',
      'bundle_price': 'Bundle',
      'add_bundle': 'Add bundle',
      'bundle_added': 'Bundle added to cart',
      'shop_bundles': 'Shop bundles',
      'inspiration': 'Inspiration',
      'inspiration_title': 'Ideas from stylists and plant parents',
      'inspiration_subtitle': 'Swipe through quick tips and cozy scenes.',
      'get_inspired': 'Get inspired',
      'save_idea': 'Saved for later',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all read',
      'mark_read': 'Mark read',
      'empty_notifications': 'You are all caught up! No new notifications.',
      'support': 'Support & FAQ',
      'help_center_subtitle': 'Quick answers and ways to reach us.',
      'support_header': 'Need more help?',
      'faqs': 'FAQs',
      'contact_support': 'Contact support',
      'chat_now': 'Live chat (mock)',
      'support_email': 'Email support',
      'support_call': 'Request a call',
      'support_notes': 'We respond within one business day for mock tickets.',
      'support_success': 'Request sent! We will get back shortly.',
      'support_cards': 'Guided help',
      'support_care': 'Care troubleshooting',
      'support_care_desc': 'Solve yellow leaves, droop, or overwatering.',
      'support_delivery': 'Delivery updates',
      'support_delivery_desc': 'Track shipments or report delays.',
      'support_payments': 'Payments & refunds',
      'support_payments_desc': 'Receipts, promo codes, and mock refunds.',
      'faq_shipping': 'How long does shipping take?',
      'faq_shipping_answer': 'Most orders ship within 2-3 days and arrive within a week.',
      'faq_care': 'How do I keep plants alive after delivery?',
      'faq_care_answer': 'Check the included guides, keep soil slightly moist, and provide indirect light.',
      'faq_returns': 'Can I return a damaged plant?',
      'faq_returns_answer': 'Yes, report within 48 hours with photos and we will replace it.',
      'gifting_center': 'Gifting',
      'gifting_hero_title': 'Send it gift-ready',
      'gifting_hero_body': 'Choose wraps, add a note, and bundle instant savings.',
      'gift_cta': 'Grab a coupon',
      'wrap_style': 'Wrap style',
      'gift_message': 'Gift message',
      'gift_message_hint': 'Add a sweet note to include with the delivery.',
      'gift_recommendations': 'Curated gift picks',
      'wrap_label': 'Wrap: {color}',
      'add_gift': 'Add gift',
      'gift_added': 'Gift bundle added to cart',
      'gifting_hint': 'Wraps, ribbons, and cards',
      'diagnostics_hint': 'Check symptoms & fixes',
      'onboard_title_1': 'Fresh greenery',
      'onboard_desc_1': 'Discover curated indoor and outdoor plants.',
      'onboard_title_2': 'Smart care tips',
      'onboard_desc_2': 'Know the right light, water, and humidity.',
      'onboard_title_3': 'Style your home',
      'onboard_desc_3': 'Build a calming corner with plants.',
    },
    'ar': {
      'app_name': 'بلانتس فريشر',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'guest': 'الدخول كضيف',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'cart': 'السلة',
      'profile': 'الملف الشخصي',
      'search': 'ابحث عن النباتات أو العلامات...',
      'add_to_cart': 'أضف للسلة',
      'add_to_compare': 'أضف للمقارنة',
      'ai_info': 'معلومات بالذكاء الاصطناعي',
      'compare': 'مقارنة',
      'empty_compare': 'لا توجد نباتات للمقارنة بعد',
      'clear_all': 'مسح الكل',
      'favorites': 'المفضلة',
      'empty_favorites': 'احفظ النباتات المفضلة لتعود إليها سريعاً لاحقاً.',
      'guides': 'أدلة العناية',
      'search_guides': 'ابحث في الأدلة...',
      'empty_guides': 'لا توجد أدلة مطابقة حالياً',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'pay': 'ادفع',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'theme': 'المظهر',
      'language': 'اللغة',
      'dark_mode': 'الوضع الليلي',
      'primary_color': 'اللون الأساسي',
      'logout': 'تسجيل الخروج',
      'welcome': 'أهلاً بك',
      'hi_guest': 'مرحباً محب النباتات',
      'checkout': 'إتمام الشراء',
      'orders': 'الطلبات',
      'success_title': 'تهانينا!',
      'success_subtitle': 'تم تنفيذ طلبك بنجاح',
      'back_home': 'العودة للرئيسية',
      'view_orders': 'عرض الطلبات',
      'promo_code': 'رمز الخصم',
      'apply': 'تطبيق',
      'apply_now': 'استخدم الآن',
      'coupons': 'القسائم',
      'coupon_center': 'مركز القسائم',
      'browse_coupons': 'تصفح القسائم',
      'applied_coupon': 'تم تطبيق {code}',
      'coupon_applied': 'تم تطبيق الكوبون {code} بقيمة {value}',
      'invalid_coupon': 'كوبون غير صالح',
      'expired_coupon': 'انتهت صلاحية الكوبون',
      'min_spend_coupon': 'يتطلب حد أدنى {min}',
      'min_spend': 'حد أدنى {min}',
      'discount': 'خصم',
      'saved_cards': 'البطاقات المحفوظة',
      'add_card': 'أضف بطاقة جديدة',
      'stores': 'الفروع',
      'addresses': 'العناوين',
      'manage_addresses': 'إدارة العناوين',
      'shipping_address': 'عنوان الشحن',
      'add_address': 'إضافة عنوان',
      'empty_addresses': 'لا توجد عناوين بعد، أضف واحداً لتسهيل الدفع.',
      'empty_cart': 'سلتك فارغة',
      'categories': 'التصنيفات',
      'featured': 'مميزة',
      'recently_viewed': 'تم استعراضها حديثاً',
      'empty_recent': 'تصفح بعض النباتات لملء هذه القائمة باختياراتك.',
      'journal': 'دفتر اليوميات',
      'journal_hint': 'سجل إنجازاتك وروتين نباتاتك وحالتها.',
      'empty_journal': 'لا توجد ملاحظات بعد. أضف قصتك النباتية الأولى.',
      'add_entry': 'إضافة ملاحظة',
      'new_entry': 'ملاحظة جديدة',
      'title_hint': 'العنوان',
      'note_hint': 'ماذا حدث؟',
      'save_entry': 'حفظ الملاحظة',
      'insights': 'الإحصائيات',
      'insights_entry': 'لوحة توضح سلسلة العناية والإنفاق والمفضلة.',
      'impact_overview': 'نظرة التأثير',
      'total_spend': 'إجمالي الإنفاق',
      'care_streak': 'سلسلة العناية',
      'care_streak_body': 'حافظ على الري والرش والتغذية بانتظام.',
      'care_completed': 'مهام مكتملة',
      'care_now_hint': 'حافظ على السلسلة',
      'week_view': 'عرض الأسبوع',
      'hydration_chart': 'الري (لتر)',
      'sun_chart': 'الضوء (ساعات)',
      'recent_activity': 'آخر الأنشطة',
      'insight_highlights': 'نقاط لامعة',
      'carbon_offset': 'بصمة أكثر خضاراً',
      'carbon_offset_body': 'حديقتك المنزلية تعوض عدة كجم من ثاني أكسيد الكربون شهرياً.',
      'care_win': 'نجاحات العناية',
      'care_win_body': 'المهام الصغيرة المتكررة تبقي النباتات مزدهرة.',
      'restock_hint': 'تسوق بذكاء',
      'restock_hint_body': 'الحزم والكوبونات تخفض رسوم التوصيل في الطلب القادم.',
      'orders_count': '{count} طلبات متعقبة',
      'favorites_count': '{count} مفضلة محفوظة',
      'favorites_body': 'احفظ النباتات المفضلة لتخصيص النصائح والتوصيات.',
      'last_viewed': 'آخر مشاهدة: {name}',
      'recent_prompt': 'عد للتفاصيل أو أضفها للسلة.',
      'bundle_story': 'إضاءات الباقات',
      'calm': 'هادئ',
      'thriving': 'مزدهر',
      'sensitive': 'حساس',
      'glossy': 'لامع',
      'whats_new': 'ما الجديد',
      'updates_hint': 'اطلع على ملاحظات الإصدار وآخر التحسينات.',
      'mark_all_read': 'تمييز كمقروء',
      'new': 'جديد',
      'indoor': 'داخلي',
      'outdoor': 'خارجي',
      'flowers': 'زهور',
      'cactus': 'صبار',
      'tools': 'أدوات',
      'easy': 'سهل',
      'medium': 'متوسط',
      'hard': 'صعب',
      'load_more': 'المزيد',
      'system_mode': 'حسب النظام',
      'added_favorite': 'تمت الإضافة للمفضلة',
      'removed_favorite': 'تمت الإزالة من المفضلة',
      'pay_securely': 'ادفع بأمان',
      'card_holder': 'صاحب البطاقة',
      'card_number': 'رقم البطاقة',
      'expiry': 'انتهاء',
      'cvc': 'رمز الأمان',
      'save_card': 'حفظ البطاقة لاحقاً',
      'label_hint': 'تسمية (منزل، مكتب...)',
      'full_name': 'الاسم الكامل',
      'phone': 'الهاتف',
      'city': 'المدينة',
      'street': 'الشارع',
      'set_default': 'تعيين كافتراضي',
      'default_address': 'افتراضي',
      'save': 'حفظ',
      'ai_mock_title': 'معلومات بالذكاء الاصطناعي (تجريبية)',
      'ai_mock_body': 'ستظهر النصائح الذكية هنا مستقبلاً بدون أي طلبات خارجية.',
      'diagnostics': 'طبيب النباتات',
      'diagnostics_headline': 'حل المشكلات بسرعة',
      'diagnostics_subtitle': 'تعرف على الأعراض وضع علامة تم الإصلاح لتسعد الأوراق.',
      'severity_all': 'الكل',
      'severity_low': 'منخفض',
      'severity_medium': 'متوسط',
      'severity_high': 'عالٍ',
      'table_property': 'خاصية',
      'table_price': 'السعر',
      'table_height': 'الارتفاع',
      'table_temperature': 'درجة الحرارة',
      'table_humidity': 'الرطوبة',
      'empty_catalog': 'لا توجد نباتات مطابقة للبحث أو الفلاتر حالياً',
      'all': 'الكل',
      'clear': 'مسح',
      'open': 'فتح',
      'read_now': 'اقرأ الآن',
      'completed': 'تم الإنجاز',
      'minutes': 'دقيقة',
      'close': 'إغلاق',
      'about': 'حول التطبيق',
      'about_description': 'بلانتس فريشر تجربة تسوق تجريبية برسوميات سلسة ودعم للغتين.',
      'about_highlights': 'أهم المزايا',
      'about_feature_theme': 'تخصيص المظهر والوضع الليلي واختيار اللون الأساسي',
      'about_feature_compare': 'مقارنة حتى ثلاثة نباتات جنباً إلى جنب',
      'about_feature_checkout': 'سلة شراء، خصم ودفع بدون أي خدمات خارجية',
      'about_feature_localization': 'إنجليزي وعربي مع دعم RTL كامل',
      'contact': 'تواصل',
      'contact_email': 'support@plantsfresher.app',
      'contact_message': 'يسعدنا تلقي ملاحظاتكم واقتراحات المزايا.',
      'version_1': 'إصدار تجريبي 1.0',
      'built_with_flutter': 'مصمم بفلتر',
      'guest_user': 'مستخدم زائر',
      'member_user': 'مستخدم مسجل',
      'order_date': 'تاريخ الطلب',
      'order_status': 'الحالة',
      'status_processing': 'قيد التنفيذ',
      'status_packed': 'تم التجهيز',
      'status_shipped': 'تم الشحن',
      'status_out_for_delivery': 'جاري التسليم',
      'status_delivered': 'تم التوصيل',
      'track_order': 'تتبع الطلب',
      'order_timeline': 'خط سير الطلب',
      'order_progress': 'التقدم',
      'tracking_updates': 'تحديثات التتبع',
      'estimated_delivery': 'التسليم المتوقع',
      'checkpoint_placed': 'تم إنشاء الطلب',
      'checkpoint_packed': 'تم تجهيز الطلب',
      'checkpoint_shipped': 'تم الشحن',
      'checkpoint_out_for_delivery': 'في طريق التسليم',
      'checkpoint_delivered': 'تم التسليم',
      'track_hint': 'تابع كل خطوة حتى تصل نباتاتك.',
      'reorder': 'أعد الطلب',
      'downtown_branch': 'فرع وسط المدينة',
      'uptown_branch': 'فرع العليا',
      'harbor_branch': 'فرع الميناء',
      'added_to_cart': 'تمت إضافة العناصر للسلة',
      'care_schedule': 'جدول العناية',
      'care_calendar': 'تقويم العناية',
      'care_overview': 'نظرة سريعة على المهام',
      'care_overview_subtitle': 'اضغط على التاريخ لرؤية مهام الري والرش.',
      'due_today': '{count} اليوم',
      'upcoming_tasks': '{count} قادمة',
      'open_calendar': 'فتح التقويم',
      'due_tasks_for': 'مهام يوم {date}',
      'no_tasks_day': 'لا توجد مهام لهذا اليوم. استمتع بجدول هادئ!',
      'month_label': '{month} · {year}',
      'calendar_shortcut': 'عرض تقويم العناية الشهري',
      'care_headline': 'حافظ على ازدهار النباتات',
      'care_subtitle': 'تذكيرات بالري والرش وتدوير النباتات في الوقت المناسب.',
      'view_up_next': 'اعرض التالي',
      'up_next': 'القادم',
      'due_now': 'مستحق الآن',
      'due_in_hours': 'متبقي {hours} ساعة',
      'due_in_days': 'متبقي {days} يوم',
      'snooze': 'تأجيل',
      'care_empty': 'لا مهام عناية حالياً - أضف نباتات لتبدأ المتابعة!',
      'rewards': 'المكافآت',
      'your_points': 'نقاطك',
      'next_reward_hint': 'واصل العناية بالنباتات لفتح الميزة التالية.',
      'earned_badges': 'الأوسمة المحققة',
      'no_badges': 'لم تحصل على أوسمة بعد — أكمل المهام لتحصل عليها.',
      'reset_badges': 'إعادة ضبط الأوسمة',
      'quick_actions': 'إجراءات سريعة',
      'finish_guide': 'أكمل دليلاً',
      'complete_care': 'أنهِ مهمة عناية',
      'favorite_plant': 'أضف نباتاً للمفضلة',
      'points_added': 'تم إضافة النقاط!',
      'redeem': 'استبدال',
      'free_delivery': 'توصيل مجاني',
      'pot_upgrade': 'ترقية أصيص',
      'surprise_seed': 'حزمة بذور مفاجئة',
      'redeemed': 'تم الاستبدال! استمتع بالمكافأة.',
      'pts': 'نقطة',
      'view_rewards': 'عرض المكافآت',
      'reward_hint': 'استبدل نقاطك بمزايا',
      'referrals': 'الإحالات',
      'invite_title': 'ادعُ أصدقاءك وازرعوا معاً',
      'invite_body': 'شارك رمزك لتحصل على نقاط إضافية عند طلبهم.',
      'invite_hint': 'شارك رمزك لتحصل على مكافآت.',
      'share_now': 'شارك الآن',
      'share_code': 'رمزك',
      'copied': 'تم النسخ',
      'share_hint': 'تم نسخ الرابط للمشاركة.',
      'joined_mock': 'تم تسجيل صديق في العرض',
      'invites_sent': 'الدعوات المرسلة',
      'friends_joined': 'الأصدقاء المنضمون',
      'reward_points': 'نقاط المكافآت',
      'how_it_works': 'كيف تعمل',
      'refer_step1': 'شارك رابط الدعوة أو الرمز.',
      'refer_step2': 'يقوم الأصدقاء بأول طلب لهم.',
      'refer_step3': 'تكسبان نقاطاً لاستبدال المزايا.',
      'explore_guides': 'أدلة العناية',
      'micro_lessons': 'دروس قصيرة لنجاح نباتاتك',
      'bundles': 'الحزم',
      'bundle_headline': 'حزم منسقة للهدايا أو لتجميل الغرفة',
      'bundle_subtitle': 'مجموعات جاهزة للشحن مع أصص وبطاقات.',
      'great_value': 'قيمة رائعة',
      'curated_sets': 'مجموعات مختارة',
      'bundle_price': 'الحزمة',
      'add_bundle': 'أضف الحزمة',
      'bundle_added': 'تمت إضافة الحزمة للسلة',
      'shop_bundles': 'تسوق الحزم',
      'inspiration': 'إلهام',
      'inspiration_title': 'أفكار من منسقي النباتات والمستخدمين',
      'inspiration_subtitle': 'تصفح نصائح سريعة ومشاهد دافئة.',
      'get_inspired': 'استلهم الآن',
      'save_idea': 'تم الحفظ لاحقاً',
      'notifications': 'الإشعارات',
      'mark_all_read': 'تعليم الكل كمقروء',
      'mark_read': 'تعليم كمقروء',
      'empty_notifications': 'لا توجد إشعارات جديدة، كل شيء جاهز!',
      'support': 'الدعم والأسئلة الشائعة',
      'help_center_subtitle': 'إجابات سريعة وطرق للتواصل معنا.',
      'support_header': 'تحتاج مساعدة إضافية؟',
      'faqs': 'الأسئلة الشائعة',
      'contact_support': 'تواصل مع الدعم',
      'chat_now': 'محادثة فورية (وهمية)',
      'support_email': 'مراسلة البريد',
      'support_call': 'طلب اتصال',
      'support_notes': 'نرد خلال يوم عمل واحد للطلبات الوهمية.',
      'support_success': 'تم إرسال الطلب! سنعاود التواصل قريباً.',
      'support_cards': 'مساعدة موجهة',
      'support_care': 'حلول العناية',
      'support_care_desc': 'عالج إصفرار الأوراق أو الذبول أو كثرة السقي.',
      'support_delivery': 'تحديثات التوصيل',
      'support_delivery_desc': 'تتبع الشحنات أو أبلغ عن التأخير.',
      'support_payments': 'المدفوعات والاسترداد',
      'support_payments_desc': 'الإيصالات، الأكواد، والاسترداد الوهمي.',
      'faq_shipping': 'كم يستغرق الشحن؟',
      'faq_shipping_answer': 'تُشحن أغلب الطلبات خلال 2-3 أيام وتصل خلال أسبوع.',
      'faq_care': 'كيف أحافظ على النبات بعد التوصيل؟',
      'faq_care_answer': 'اتبع الأدلة المرفقة، حافظ على رطوبة خفيفة وضوء غير مباشر.',
      'faq_returns': 'هل يمكن إرجاع النبات المتضرر؟',
      'faq_returns_answer': 'نعم، أبلغ خلال 48 ساعة مع صور لنستبدله.',
      'gifting_center': 'الهدايا',
      'gifting_hero_title': 'أرسلها جاهزة كهدية',
      'gifting_hero_body': 'اختر التغليف، أضف رسالة، واضمن مكافآت الخصم فوراً.',
      'gift_cta': 'احصل على كوبون',
      'wrap_style': 'شكل التغليف',
      'gift_message': 'رسالة الهدية',
      'gift_message_hint': 'أضف رسالة لطيفة مرفقة مع التوصيل.',
      'gift_recommendations': 'اختيارات منسقة للهدايا',
      'wrap_label': 'التغليف: {color}',
      'add_gift': 'أضف كهدية',
      'gift_added': 'تمت إضافة الهدية للسلة',
      'gifting_hint': 'تغليف وأشرطة وبطاقات',
      'diagnostics_hint': 'تفقد الأعراض والحلول',
      'onboard_title_1': 'خضرة طازجة',
      'onboard_desc_1': 'اكتشف نباتات داخلية وخارجية مختارة بعناية.',
      'onboard_title_2': 'نصائح عناية ذكية',
      'onboard_desc_2': 'تعرف على الإضاءة والري والرطوبة المناسبة.',
      'onboard_title_3': 'زين منزلك',
      'onboard_desc_3': 'اصنع زاوية هادئة بالنباتات.',
    },
  };

  String t(String key) => _localizedValues[locale.languageCode]?[key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
