name: plants_fresher
description: A plants e-commerce experience with theming, localization, and rich UI.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  iconly: ^1.0.1
  flutter_animate: ^4.5.0

flutter:
  uses-material-design: true
